const SEARCH_MOVIES_REQUEST: string = "SEARCH_MOVIES_REQUEST";
const SEARCH_MOVIES_SUCCESS: string = "SEARCH_MOVIES_SUCCESS";
const SEARCH_MOVIES_FAILURE: string = "SEARCH_MOVIES_FAILURE";

export { SEARCH_MOVIES_REQUEST, SEARCH_MOVIES_SUCCESS, SEARCH_MOVIES_FAILURE };
